site_name: Sample website
site_author: Piotr Machura
docs_dir: src

theme:
  name: cosmo
  nav_style: dark
  custom_dir: theme

markdown_extensions:
  - extra
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown_del_ins

nav:
  - Projects:
    - 'Coming soon': ''
  - Blog:
    - 'blog/3.md'
    - 'blog/2.md'
    - 'blog/1.md'
