site_name: Piotr Machura
site_author: Piotr Machura
docs_dir: src
repo_url: https://github.com/piotr-machura/
edit_uri: ''

theme:
  name: cosmo
  nav_style: dark
  custom_dir: 'theme'

markdown_extensions:
  - extra
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown_del_ins

nav:
  - Projects:
    - 'Genetic programming': 'https://github.com/piotr-machura/cartesian-genetic-programming'
    - 'Complex solver': 'https://github.com/piotr-machura/complex-solver'
    - 'Arch Linux setup' : 'arch-setup.md'
  - Blog:
    - 'blog/3.md'
    - 'blog/2.md'
    - 'blog/1.md'
