site_name: Mkdocs website
site_author: Piotr Machura
docs_dir: src

theme:
  name: cosmo
  nav_style: dark

extra_javascript:
    # MathJax for LaTex math support
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - css/fonts.css

markdown_extensions:
  - extra
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown_del_ins
