site_name: Piotr Machura
site_author: Piotr Machura
docs_dir: src
repo_url: https://github.com/piotr-machura/
edit_uri: ''

theme:
  name: cosmo
  nav_style: dark
  custom_dir: 'theme'

markdown_extensions:
  - extra
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown_del_ins

nav:
  - Projects:
    - 'Arch Linux' : 'arch-setup.md'
    - 'Personal server' : 'personal-server.md'
  - Contact: 'contact.md'
  - Mail: '/mail'
