site_name: Mkdocs website
site_author: Piotr Machura
docs_dir: src

theme:
  name: yeti
  nav_style: dark
  highlightjs: true

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - css/nord.css
  - https://fonts.googleapis.com/css2?family=Fira+Mono:wght@500&display=swap

markdown_extensions:
  - extra
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown_del_ins
